#!/bin/bash

###################################
# Author: Purnima
# Date: Sept 27
# Version: v1
#
# This script will report the AWS resource usage

set -x

# Print list of S3 buckets and save to a file
echo "Print list of S3 buckets"
aws s3 ls > s3_buckets.txt

# Print list of EC2 instances and save to a file
echo "Print list of EC2 instances"
aws ec2 describe-instances | jq '.Reservations[].Instances[].InstanceId' > ec2_instances.txt

# Print list of Lambda functions and save to a file
echo "Print list of Lambda functions"
aws lambda list-functions > lambda_functions.txt

# Print list of IAM users and save to a file
echo "Print list of IAM users"
aws iam list-users > iam_users.txt


